use_nerdfont = false
notify = false
volnorm = true


[theme]
primary = "light white"
secondary = "black"
title = "cyan"
playing = "cyan"
highlight = "blue"
highlight_bg = "light black"
error = "light white"
error_bg = "red"
statusbar = "cyan"
statusbar_progress = "cyan"
cmdline = "black"
cmdline_bg = "light white"
